/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Invite } from "./Invite";
import { InviteCountArgs } from "./InviteCountArgs";
import { InviteFindManyArgs } from "./InviteFindManyArgs";
import { InviteFindUniqueArgs } from "./InviteFindUniqueArgs";
import { CreateInviteArgs } from "./CreateInviteArgs";
import { UpdateInviteArgs } from "./UpdateInviteArgs";
import { DeleteInviteArgs } from "./DeleteInviteArgs";
import { InviteService } from "../invite.service";
@graphql.Resolver(() => Invite)
export class InviteResolverBase {
  constructor(protected readonly service: InviteService) {}

  async _invitesMeta(
    @graphql.Args() args: InviteCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Invite])
  async invites(@graphql.Args() args: InviteFindManyArgs): Promise<Invite[]> {
    return this.service.invites(args);
  }

  @graphql.Query(() => Invite, { nullable: true })
  async invite(
    @graphql.Args() args: InviteFindUniqueArgs
  ): Promise<Invite | null> {
    const result = await this.service.invite(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Invite)
  async createInvite(@graphql.Args() args: CreateInviteArgs): Promise<Invite> {
    return await this.service.createInvite({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Invite)
  async updateInvite(
    @graphql.Args() args: UpdateInviteArgs
  ): Promise<Invite | null> {
    try {
      return await this.service.updateInvite({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Invite)
  async deleteInvite(
    @graphql.Args() args: DeleteInviteArgs
  ): Promise<Invite | null> {
    try {
      return await this.service.deleteInvite(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
