/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DiscordUserService } from "../discordUser.service";
import { DiscordUserCreateInput } from "./DiscordUserCreateInput";
import { DiscordUser } from "./DiscordUser";
import { DiscordUserFindManyArgs } from "./DiscordUserFindManyArgs";
import { DiscordUserWhereUniqueInput } from "./DiscordUserWhereUniqueInput";
import { DiscordUserUpdateInput } from "./DiscordUserUpdateInput";
import { SubscriptionFindManyArgs } from "../../subscription/base/SubscriptionFindManyArgs";
import { Subscription } from "../../subscription/base/Subscription";
import { SubscriptionWhereUniqueInput } from "../../subscription/base/SubscriptionWhereUniqueInput";

export class DiscordUserControllerBase {
  constructor(protected readonly service: DiscordUserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DiscordUser })
  async createDiscordUser(
    @common.Body() data: DiscordUserCreateInput
  ): Promise<DiscordUser> {
    return await this.service.createDiscordUser({
      data: {
        ...data,

        role: data.role
          ? {
              connect: data.role,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        userId: true,
        username: true,

        role: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [DiscordUser] })
  @ApiNestedQuery(DiscordUserFindManyArgs)
  async discordUsers(@common.Req() request: Request): Promise<DiscordUser[]> {
    const args = plainToClass(DiscordUserFindManyArgs, request.query);
    return this.service.discordUsers({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        userId: true,
        username: true,

        role: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DiscordUser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async discordUser(
    @common.Param() params: DiscordUserWhereUniqueInput
  ): Promise<DiscordUser | null> {
    const result = await this.service.discordUser({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        userId: true,
        username: true,

        role: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DiscordUser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateDiscordUser(
    @common.Param() params: DiscordUserWhereUniqueInput,
    @common.Body() data: DiscordUserUpdateInput
  ): Promise<DiscordUser | null> {
    try {
      return await this.service.updateDiscordUser({
        where: params,
        data: {
          ...data,

          role: data.role
            ? {
                connect: data.role,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          userId: true,
          username: true,

          role: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DiscordUser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteDiscordUser(
    @common.Param() params: DiscordUserWhereUniqueInput
  ): Promise<DiscordUser | null> {
    try {
      return await this.service.deleteDiscordUser({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          userId: true,
          username: true,

          role: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/subscriptions")
  @ApiNestedQuery(SubscriptionFindManyArgs)
  async findSubscriptions(
    @common.Req() request: Request,
    @common.Param() params: DiscordUserWhereUniqueInput
  ): Promise<Subscription[]> {
    const query = plainToClass(SubscriptionFindManyArgs, request.query);
    const results = await this.service.findSubscriptions(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        subscriptionId: true,
        tier: true,

        discordUser: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/subscriptions")
  async connectSubscriptions(
    @common.Param() params: DiscordUserWhereUniqueInput,
    @common.Body() body: SubscriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      subscriptions: {
        connect: body,
      },
    };
    await this.service.updateDiscordUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/subscriptions")
  async updateSubscriptions(
    @common.Param() params: DiscordUserWhereUniqueInput,
    @common.Body() body: SubscriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      subscriptions: {
        set: body,
      },
    };
    await this.service.updateDiscordUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/subscriptions")
  async disconnectSubscriptions(
    @common.Param() params: DiscordUserWhereUniqueInput,
    @common.Body() body: SubscriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      subscriptions: {
        disconnect: body,
      },
    };
    await this.service.updateDiscordUser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
